"""add device hardware id

Revision ID: 7afb88c7d64f
Revises: 717cb7c97e95
Create Date: 2026-08-31 20:21:35.027479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afb88c7d64f'
down_revision: Union[str, Sequence[str], None] = '717cb7c97e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('hardware_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_devices_hardware_id'), 'devices', ['hardware_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_hardware_id'), table_name='devices')
    op.drop_column('devices', 'hardware_id')
    # ### end Alembic commands ###
