"""add device location

Revision ID: 91bef69f509d
Revises: 7afb88c7d64f
Create Date: 2026-09-05 13:44:57.833568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bef69f509d'
down_revision: Union[str, Sequence[str], None] = '7afb88c7d64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'location_updated_at')
    op.drop_column('devices', 'longitude')
    op.drop_column('devices', 'latitude')
    # ### end Alembic commands ###
