"""add device api token

Revision ID: b037141122fd
Revises: 91bef69f509d
Create Date: 2026-09-05 14:12:30.504014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b037141122fd'
down_revision: Union[str, Sequence[str], None] = '91bef69f509d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('api_token_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_devices_api_token_hash'), 'devices', ['api_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_api_token_hash'), table_name='devices')
    op.drop_column('devices', 'api_token_hash')
    # ### end Alembic commands ###
