"""add measurements and sensor values

Revision ID: b4d56781ac45
Revises: a7a96c136dcb
Create Date: 2026-08-30 18:55:53.302657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d56781ac45'
down_revision: Union[str, Sequence[str], None] = 'a7a96c136dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_measurements_device_timestamp', 'measurements', ['device_id', 'timestamp'], unique=False)
    op.create_table('sensor_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('light', sa.Float(), nullable=True),
    sa.Column('pm1', sa.Float(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm4', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('nc05', sa.Float(), nullable=True),
    sa.Column('nc10', sa.Float(), nullable=True),
    sa.Column('nc25', sa.Float(), nullable=True),
    sa.Column('nc40', sa.Float(), nullable=True),
    sa.Column('nc100', sa.Float(), nullable=True),
    sa.Column('typical_particle_size', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement_id')
    )
    op.add_column('devices', sa.Column('firmware_version', sa.String(length=30), nullable=True))
    op.add_column('devices', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true(),))
    op.add_column('devices', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"),))
    op.add_column('devices', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    op.alter_column("devices", "active", server_default=None,)
    op.alter_column("devices", "created_at", server_default=None,)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_seen')
    op.drop_column('devices', 'created_at')
    op.drop_column('devices', 'active')
    op.drop_column('devices', 'firmware_version')
    op.drop_table('sensor_values')
    op.drop_index('ix_measurements_device_timestamp', table_name='measurements')
    op.drop_table('measurements')
    # ### end Alembic commands ###
